name: SudoForce
version: '${project.version}'
main: me.zombieman.dev.sudoforce.SudoForce
api-version: '1.13'

commands:
  sudoforce:
    aliases:
      - sudo
      - sf
    permission: sudoforce.command.sudoforce